USE master
DROP DATABASE IF EXISTS TicketMaster

CREATE DATABASE TicketMaster
USE TicketMaster

CREATE TABLE Users(
	[ID] INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	[Name] NVARCHAR(255) NOT NULL,
	[Login] NVARCHAR(255) NOT NULL UNIQUE,
	[Password] NVARCHAR(255) NOT NULL UNIQUE,
	[IsSysAdmin] BIT DEFAULT 0 NOT NULL
    [IsSpecial] INT NOT NULL
	);

CREATE TABLE Events(
	[ID] INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	[Name] NVARCHAR(255) NOT NULL,
	[Description] NVARCHAR(MAX) NOT NULL,
	[EventStart] DATETIME NOT NULL,
	[EventEnd] DATETIME,
	[Location] NVARCHAR(MAX),
	[MaxTickets] INT NOT NULL,
	[SoldTickets] INT NOT NULL,
	[CreatedBy] INT FOREIGN KEY REFERENCES [Users](ID) NOT NULL
	);

CREATE TABLE Customers(
	[ID] INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	[Name] NVARCHAR(255) NOT NULL,
	[EMail] NVARCHAR(255)
	);


CREATE TABLE Tickets(
	[ID] UNIQUEIDENTIFIER DEFAULT NEWID() PRIMARY KEY NOT NULL,
	[CustomerID] INT FOREIGN KEY REFERENCES [Customers](ID) NOT NULL,
	[EventID] INT FOREIGN KEY REFERENCES [Events](ID) NOT NULL,
	[CreatedTime] DATETIME DEFAULT GETDATE() NOT NULL,
	[IsUSed] BIT DEFAULT 0 NOT NULL,
	[SoldBy] INT FOREIGN KEY REFERENCES [Users](ID) NOT NULL
	);



